### ISSUE TITLE
Support for Sketchup 8

### ISSUE THREAD

**Issue by FMZ007** [Eneroth3/open-newer-version#4]
Hello, nice plugin. Is it possible to make it work for Sketchup 8 (last free commercial version)?
We have a mix of version here and always painful to open a file in meeting room where we have SKP 8.

Thanks,

**Comment by Eneroth3** [comment]
Hi

Creating plugins for old SU versions is something of a pain. A lot of new features have been added to the API since, bugs have been fixed and the Ruby version has been updated multiple times. SketchUp 2014 was the first version with version 2 of Ruby and getting a plugin to work in older versions typically requires more and uglier code, making it more cumbersome to create and maintain.

I have personally chosen to make SketchUp 2014 the oldest version I ever put down extra work to get a plugin working in. Some plugins of mine work in older versions by chance, several require a much newer version.

While I consider it outside the scope of this repo to support such old SU versions, you are free to fork it and see if you can get it to work. A totally different approach could be to update your licenses and support future SketchUp development.

**Comment by FMZ007** [comment]
Ok I understand your technical point of view.
It could have been interesting for us because 3D draftsmen have 2018 licence and other use SKP 8 as a viewer (last free commercial version).
I'll try to find another way...

Thank nevertheless,
